i4ipv2:
  container_name: deedstar
  image: nginx:latest
  hostname: deedstar

#  commented out since the over-ride does not seem to prevent these being instantiated on the bridge causing startup failure
#  look for the port allocation in the docker-compose.override.yml file
  ports:
   - 3010:80
   - 3443:443
  # log_driver: "fluentd"
  volumes:
     - ./../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./../html:/usr/share/nginx/html:ro
  restart: always
  
